### ISSUE TITLE
missing sourcemap

### ISSUE THREAD

**Issue by onelson** [ddispaltro/sbt-reactjs#13]
Hi!
I added `ReactJsKeys.sourceMapInline := true` to my `build.sbt` but I'm not seeing any sourcemap output in the resulting script.
Am I doing it wrong?

**Comment by ddispaltro** [comment]
That should be it.  It should look something like this:

https://github.com/ddispaltro/sbt-reactjs/blob/master/src/sbt-test/sbt-reactjs/reacttask/out/more.js

**Comment by onelson** [comment]
Hmm. I'm unable to detect a critical difference in what you've got in your test and what I have in my project, and yet the sourcemap blob is missing in my case.

What can I do to help trace this through? Not much in the project as yet, but here's the current (in case it's of interest): https://bitbucket.org/activatefan/activatefan.club/src/f561739256147c1e4b6c1c6a4c9898ee72013690/?at=profile

**Comment by ddispaltro** [comment]
Hmm not sure.  Run sbt. Type `; clean ; assets` and put that in a gist.

**Comment by onelson** [comment]
Looks like a ghost in the machine. Post, `sbt clean` everything is coming out as expected. Sorry to waste your time!
