### ISSUE TITLE
How to pass harmony flag?

### ISSUE THREAD

**Issue by anildigital** [ddispaltro/sbt-reactjs#16]
I have following line in plugins.sbt

```
addSbtPlugin("com.github.ddispaltro" % "sbt-reactjs" % "0.5.0")
```
How to pass harmony flag?

**Comment by ddispaltro** [comment]
Check here, https://github.com/ddispaltro/sbt-reactjs/blob/master/src/sbt-test/sbt-reactjs/reacttask/build.sbt
