### ISSUE TITLE
Minification of output javascript

### ISSUE THREAD

**Issue by randak** [ddispaltro/sbt-reactjs#6]
From what I can tell, there does not appear to be an option to output minified javascript. The sbt-coffeescript project as well as the command line jsx compiler support this, so it would be nice to have this feature here as well.

**Comment by dsarosi** [comment]
Agree, it doesn't support pipelineStages.

**Comment by ddispaltro** [comment]
If I remember correctly, this works similarly to the coffeescript plugin, which is different that how the gzip plugins works. Basically assets get transpiled, then I think later in the asset pipeline everything gets minified.  It might have changed recently, I haven't used it lately.

**Comment by ddispaltro** [comment]
Closing for now.
