### ISSUE TITLE
Upgrade to reactjs 0.13

### ISSUE THREAD

**Issue by gabadi** [ddispaltro/sbt-reactjs#8]
There is a new version of reactjs, it could be good to update the version, i've already crated the issue in webjars

https://github.com/webjars/react/issues/15

**Comment by ddispaltro** [comment]
I am not using this much these days.  If you want to do the work on the PR ill merge as long as it passes.

**Comment by gabadi** [comment]
The update is done and is working in trevis

https://github.com/ddispaltro/sbt-reactjs/pull/11

**Comment by ddispaltro** [comment]
Merged

**Comment by ddispaltro** [comment]
And published

**Comment by gabadi** [comment]
Thanks!
